    # self.screen.addstr(8, 3, "Username: ")
    # self.screen.hline(8, 13, "_", 32)
    # # username = self.screen.getstr(7, 13, 32)
    # self.screen.addstr(10, 3, "Contract number: ")
    # self.screen.hline(10, 20, "_", 25)
    # # cn = self.screen.getstr(9, 13, 25)
